
package com.pay;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PayingImplService", targetNamespace = "http://pay.com/", wsdlLocation = " ")
public class PayingImplService
    extends Service
{

    private final static URL PAYINGIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PAYINGIMPLSERVICE_EXCEPTION;
    private final static QName PAYINGIMPLSERVICE_QNAME = new QName("http://pay.com/", "PayingImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/PayService/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAYINGIMPLSERVICE_WSDL_LOCATION = url;
        PAYINGIMPLSERVICE_EXCEPTION = e;
    }

    public PayingImplService() {
        super(__getWsdlLocation(), PAYINGIMPLSERVICE_QNAME);
    }

    public PayingImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYINGIMPLSERVICE_QNAME, features);
    }

    public PayingImplService(URL wsdlLocation) {
        super(wsdlLocation, PAYINGIMPLSERVICE_QNAME);
    }

    public PayingImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYINGIMPLSERVICE_QNAME, features);
    }

    public PayingImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PayingImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PayInterface
     */
    @WebEndpoint(name = "PayingImplPort")
    public PayInterface getPayingImplPort() {
        return super.getPort(new QName("http://pay.com/", "PayingImplPort"), PayInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PayInterface
     */
    @WebEndpoint(name = "PayingImplPort")
    public PayInterface getPayingImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://pay.com/", "PayingImplPort"), PayInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYINGIMPLSERVICE_EXCEPTION!= null) {
            throw PAYINGIMPLSERVICE_EXCEPTION;
        }
        return PAYINGIMPLSERVICE_WSDL_LOCATION;
    }

}
